# Generated by Django 3.1.6 on 2021-02-03 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzeriaUCAB.client')),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField(default=0)),
                ('size', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzeriaUCAB.order')),
                ('pizza_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzeriaUCAB.pizza')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzeriaUCAB.ingredient')),
                ('pizza_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PizzeriaUCAB.pizza')),
            ],
        ),
    ]
